[tool.poetry]
name = "gym-tl-tools"
version = "0.1.0"
description = "Utilities to wrap gymnasium environments using TL rewards."
authors = ["Mikihisa Yuasa <myuasa2@illinois.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
